name: test run python code

on:
  push:
    branches:
      - feat/*
      - main

jobs:
  ci-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20" # Adjust the Go version as needed

      - name: Install Go dependencies
        run: go mod tidy

      - name: Build the Go app
        run: |
          GOOS=darwin GOARCH=arm64 go build -o hello-world-darwin-arm64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-world-darwin-arm64
          path: hello-world-darwin-arm64
  # ci-python:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.12"

  #     - name: Cache dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.cache/pip
  #         key: ${{ runner.os }}-pip-${{ hashFiles('pyhton/requirements.txt') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pip-

  #     - name: Install dependencies
  #       run: |
  #         pip install -r python/requirements.txt

  #     - name: Run Python script
  #       run: |
  #         python python/main.py
